### ISSUE TITLE
Update TypeScript exports to support moduleResolution bundler

### ISSUE THREAD

**Issue by kwangure** [lezer-parser/cpp#5]
[`moduleResolution: "bundler"`](https://www.typescriptlang.org/tsconfig#moduleResolution) is a recent setting added to TypeScript to support bundler setups. It's the setting you should probably be using when bundling code. With this setting TypeScript only searches for types in the exports field of the `package.json`.

It requires the following change:

```diff
 "exports": {
   "import": "./dist/index.js",
   "require": "./dist/index.cjs",
+  "types": "./dist/index.d.ts"
 },
```

This is issue is relevent to multiple @lezer packages I'm using.

**Comment by marijnh** [comment]
Should be handled by 339111b77182d91d9bce402b5842f88e1cadb1cb
